// This file is auto-generated by @hey-api/openapi-ts

export type WeatherForecast = {
    date?: string;
    temperatureC?: number;
    temperatureF?: number;
    summary?: (string) | null;
};

export type GetWeatherForecastResponse = (Array<WeatherForecast>);

export type GetWeatherForecastError = unknown;